/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/programs': typeof ProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/programs/': typeof ProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programs/$slug' | '/courses/' | '/programs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programs/$slug' | '/courses' | '/programs'
  id: '__root__' | '/' | '/programs/$slug' | '/courses/' | '/programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
